import { createTool } from '@forge-runtime/core';
import { z } from 'zod';
import { createArtifactStore, type ArtifactType } from './store';

export function createArtifactTools(db: Parameters<typeof createArtifactStore>[0], agentId: string) {
  const store = createArtifactStore(db);

  const list_generated_artifacts = createTool({
    id: 'list_generated_artifacts',
    description:
      'List artifacts generated by this agent. You can filter by type (tts or image) to get a summary of previously generated content.',
    inputSchema: z.object({
      type: z.enum(['tts', 'image']).optional().describe('Filter by artifact type. tts = speech/audio, image = generated images.'),
      limit: z.number().int().min(1).max(100).optional().describe('Maximum number of artifacts to return. Default 20.'),
    }),
    execute: async (input) => {
      try {
        const toolId: ArtifactType | undefined = input.type === 'tts' ? 'minimax_tts' : input.type === 'image' ? 'minimax_image' : undefined;
        const artifacts = await store.listByAgent(agentId, toolId, input.limit ?? 20);

        return {
          valid: true,
          artifacts: artifacts.map((a) => ({
            artifactId: a.artifactId,
            type: a.toolId,
            path: a.filePath,
            mimeType: a.mimeType,
            createdAt: new Date(a.createdAt).toISOString(),
            metadata: a.metadata,
          })),
        };
      } catch (error) {
        return { valid: false, error: error instanceof Error ? error.message : 'Failed to list artifacts' };
      }
    },
  });

  return { list_generated_artifacts };
}