name: Bug report
description: Reportar problema
title: 'bug: '
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      placeholder: O que aconteceu?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Como reproduzir
      placeholder: Passo a passo
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true
