import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('drizzle-orm', () => ({
  eq: vi.fn((a: unknown, b: unknown) => ({ type: 'eq', a, b })),
  desc: vi.fn((col: unknown) => ({ type: 'desc', col })),
  and: vi.fn(),
  sql: vi.fn(),
  relations: vi.fn(),
}));

vi.mock('@forge-runtime/core', () => ({
  forgeDebug: vi.fn(),
}));

vi.mock('../utils/id', () => ({
  createId: vi.fn().mockReturnValue('a1b2c3d4-e5f6-7890-abcd-ef1234567890'),
}));

vi.mock('../../database/schema', () => ({
  webhookRoutes: { $columnMap: {} },
  webhookEvents: { $columnMap: {} },
}));

// Drizzle query builder is a chain of calls that returns new query builder objects.
// Each method returns the new object. We simulate this with a chain factory.
function makeChain(returnValue: unknown = undefined) {
  const chain: Record<string, any> = {};
  const methods = ['from', 'where', 'limit', 'orderBy', 'set', 'values', 'onConflictDoNothing', 'returning'];
  methods.forEach((m) => {
    chain[m] = vi.fn().mockReturnValue(returnValue !== undefined ? returnValue : chain);
  });
  // Special: where returns a chain that resolves the promise
  chain._resolveWhere = (val: unknown) => {
    const whereChain: Record<string, any> = {};
    const chainMethods = ['limit', 'orderBy', 'all'];
    chainMethods.forEach((m) => {
      whereChain[m] = vi.fn().mockReturnValue(whereChain);
    });
    whereChain.then = (cb: (v: unknown) => void) => cb(val);
    chain.where.mockReturnValue(whereChain);
    return whereChain;
  };
  return chain;
}

function createMockDb() {
  // insert() → returns a chain with values()
  // update() → returns a chain with set().where()
  // select() → returns a chain with from().where()
  // db itself only has these three methods
  return {
    insert: vi.fn(() => makeChain()),
    update: vi.fn(() => makeChain()),
    select: vi.fn(() => makeChain()),
    delete: vi.fn(() => makeChain()),
  };
}

import { createWebhookStore } from './store';

describe('createWebhookStore', () => {
  let db: ReturnType<typeof createMockDb>;

  beforeEach(() => {
    db = createMockDb();
    vi.clearAllMocks();
  });

  describe('createRoute', () => {
    it('creates a route and returns it with generated routeId', async () => {
      const store = createWebhookStore(db as any);
      const result = await store.createRoute({
        agentId: 'agent-1',
        name: 'Test Webhook',
        secret: 'my-secret-xyz',
      });
      expect(result).toMatchObject({
        // routeId generated by createId() — verify UUID format
        routeId: expect.stringMatching(
          /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
        ),
        agentId: 'agent-1',
        name: 'Test Webhook',
        secret: 'my-secret-xyz',
        isActive: 1,
      });
    });

    it('uses createId for the routeId', async () => {
      const { createId } = await import('../utils/id');
      const store = createWebhookStore(db as any);
      const result = await store.createRoute({ agentId: 'agent-1', name: 'Test' });
      // createId is called to generate routeId
      expect(createId).toHaveBeenCalled();
      // createId's return value is the routeId
      expect(result.routeId).toBe('a1b2c3d4-e5f6-7890-abcd-ef1234567890');
    });

    it('defaults secret to null when not provided', async () => {
      const store = createWebhookStore(db as any);
      const result = await store.createRoute({ agentId: 'agent-1', name: 'Test' });
      expect(result.secret).toBeNull();
    });

    it('calls db.insert with webhookRoutes', async () => {
      const store = createWebhookStore(db as any);
      await store.createRoute({ agentId: 'agent-1', name: 'Test' });
      expect(db.insert).toHaveBeenCalled();
    });

    it('logs via forgeDebug and rethrows on DB insert error', async () => {
      const { forgeDebug } = await import('@forge-runtime/core');
      db.insert.mockImplementationOnce(() => {
        const chain = makeChain();
        chain.values.mockImplementationOnce(() => {
          throw new Error('DB connection failed');
        });
        return chain;
      });
      const store = createWebhookStore(db as any);
      await expect(store.createRoute({ agentId: 'agent-1', name: 'Test' })).rejects.toThrow(
        'DB connection failed',
      );
      expect(forgeDebug).toHaveBeenCalledWith(
        expect.objectContaining({
          scope: 'webhooks-store',
          level: 'error',
          message: expect.stringContaining('createRoute DB write failed'),
        }),
      );
    });
  });

  describe('getRoute', () => {
    it('returns the route when found', async () => {
      const qb = makeChain();
      qb.from.mockReturnValueOnce(qb);
      qb._resolveWhere([
        {
          routeId: 'route-1',
          name: 'Found Route',
          agentId: 'agent-1',
          isActive: true,
          secret: 'x',
          createdAt: 1,
          updatedAt: 1,
        },
      ]);
      db.select.mockReturnValueOnce(qb);

      const store = createWebhookStore(db as any);
      const result = await store.getRoute('route-1');
      expect(result).toMatchObject({ routeId: 'route-1', name: 'Found Route' });
    });

    it('returns null when no route matches', async () => {
      const qb = makeChain();
      qb.from.mockReturnValueOnce(qb);
      qb._resolveWhere([]);
      db.select.mockReturnValueOnce(qb);

      const store = createWebhookStore(db as any);
      const result = await store.getRoute('nonexistent');
      expect(result).toBeNull();
    });

    it('logs and throws on DB error', async () => {
      const { forgeDebug } = await import('@forge-runtime/core');
      const qb = makeChain();
      qb.from.mockReturnValueOnce(qb);
      qb.where.mockImplementationOnce(() => {
        throw new Error('Read failed');
      });
      db.select.mockReturnValueOnce(qb);

      const store = createWebhookStore(db as any);
      await expect(store.getRoute('route-1')).rejects.toThrow('Read failed');
      expect(forgeDebug).toHaveBeenCalledWith(
        expect.objectContaining({
          scope: 'webhooks-store',
          level: 'error',
          message: expect.stringContaining('getRoute DB read failed'),
        }),
      );
    });
  });

  describe('listRoutesByAgent', () => {
    it('returns routes for the agent ordered by createdAt desc', async () => {
      const qb = makeChain();
      qb.from.mockReturnValueOnce(qb);
      qb._resolveWhere([{ routeId: 'route-1' }, { routeId: 'route-2' }]);
      db.select.mockReturnValueOnce(qb);

      const store = createWebhookStore(db as any);
      const result = await store.listRoutesByAgent('agent-1');
      expect(result).toHaveLength(2);
    });

    it('returns empty array when no routes exist', async () => {
      const qb = makeChain();
      qb.from.mockReturnValueOnce(qb);
      qb._resolveWhere([]);
      db.select.mockReturnValueOnce(qb);

      const store = createWebhookStore(db as any);
      const result = await store.listRoutesByAgent('agent-99');
      expect(result).toHaveLength(0);
    });

    it('logs and throws on DB error', async () => {
      const { forgeDebug } = await import('@forge-runtime/core');
      const qb = makeChain();
      qb.from.mockReturnValueOnce(qb);
      qb.where.mockImplementationOnce(() => {
        throw new Error('DB read error');
      });
      db.select.mockReturnValueOnce(qb);

      const store = createWebhookStore(db as any);
      await expect(store.listRoutesByAgent('agent-1')).rejects.toThrow('DB read error');
      expect(forgeDebug).toHaveBeenCalledWith(expect.objectContaining({ scope: 'webhooks-store' }));
    });
  });

  describe('deactivateRoute', () => {
    it('calls db.update with webhookRoutes', async () => {
      const store = createWebhookStore(db as any);
      await store.deactivateRoute('route-xyz');
      expect(db.update).toHaveBeenCalled();
    });

    it('throws and logs on DB error', async () => {
      const { forgeDebug } = await import('@forge-runtime/core');
      const chain = makeChain();
      chain.set.mockReturnValueOnce(chain);
      chain.where.mockImplementationOnce(() => {
        throw new Error('Update failed');
      });
      db.update.mockReturnValueOnce(chain);

      const store = createWebhookStore(db as any);
      await expect(store.deactivateRoute('route-xyz')).rejects.toThrow('Update failed');
      expect(forgeDebug).toHaveBeenCalledWith(
        expect.objectContaining({
          scope: 'webhooks-store',
          message: expect.stringContaining('deactivateRoute DB write failed'),
        }),
      );
    });
  });

  describe('createEvent', () => {
    it('returns kind: created with eventId when no idempotencyKey is provided', async () => {
      const store = createWebhookStore(db as any);
      const result = await store.createEvent({
        routeId: 'route-1',
        agentId: 'agent-1',
        payload: { foo: 'bar' },
        headers: { 'content-type': 'application/json' },
      });
      expect(result).toEqual({
        kind: 'created',
        eventId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      });
    });

    it('returns kind: created even with empty-string idempotencyKey (AC-3 / T9: empty key === missing)', async () => {
      const store = createWebhookStore(db as any);
      const result = await store.createEvent({
        routeId: 'route-1',
        agentId: 'agent-1',
        payload: {},
        headers: {},
        idempotencyKey: '',
      });
      expect(result).toEqual({
        kind: 'created',
        eventId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      });
    });

    it('logs and rethrows on DB error', async () => {
      const { forgeDebug } = await import('@forge-runtime/core');
      const chain = makeChain();
      chain.values.mockImplementationOnce(() => {
        throw new Error('Event insert failed');
      });
      db.insert.mockImplementationOnce(() => chain);

      const store = createWebhookStore(db as any);
      await expect(
        store.createEvent({
          routeId: 'route-1',
          agentId: 'agent-1',
          payload: {},
          headers: {},
        }),
      ).rejects.toThrow('Event insert failed');
      expect(forgeDebug).toHaveBeenCalledWith(
        expect.objectContaining({
          scope: 'webhooks-store',
          message: expect.stringContaining('createEvent DB write failed'),
        }),
      );
    });

    it('returns kind: created when idempotencyKey is provided and insert succeeds (T1: replay - first call)', async () => {
      // T1 first call: insert with idempotencyKey returns a row → 'created'.
      // We need a chain where values/onConflictDoNothing return the chain
      // (so the production code can chain), and returning() returns a thenable.
      const thenable = (val: unknown) => ({ then: (cb: (v: unknown) => void) => cb(val) });
      const insertChain = makeChain();
      insertChain.returning.mockReturnValue(thenable([{ eventId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890' }]));
      db.insert.mockImplementationOnce(() => insertChain);

      const store = createWebhookStore(db as any);
      const result = await store.createEvent({
        routeId: 'route-1', agentId: 'agent-1', payload: {}, headers: {},
        idempotencyKey: 'idem-key-1',
      });

      expect(result).toEqual({ kind: 'created', eventId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890' });
    });

    it('returns kind: duplicate with existing eventId on conflict (T1: replay - second call)', async () => {
      // T1 second call: INSERT OR IGNORE returns no row → lookup existing.
      const thenable = (val: unknown) => ({ then: (cb: (v: unknown) => void) => cb(val) });
      const insertChain = makeChain();
      insertChain.returning.mockReturnValue(thenable([]));
      // select().from().where().limit().all() needs to resolve to an array with the existing event.
      const selectChain = makeChain();
      selectChain.all = vi.fn().mockReturnValue([{ eventId: 'existing-event-id' }]);
      db.insert.mockImplementationOnce(() => insertChain);
      db.select.mockImplementationOnce(() => selectChain);

      const store = createWebhookStore(db as any);
      const result = await store.createEvent({
        routeId: 'route-1', agentId: 'agent-1', payload: {}, headers: {},
        idempotencyKey: 'idem-key-1',
      });

      expect(result).toEqual({ kind: 'duplicate', eventId: 'existing-event-id' });
    });

    it('scopes dedup to (routeId, idempotencyKey) (AC-2: same key on different routes is NOT a duplicate)', async () => {
      // AC-2: the UNIQUE constraint is on (routeId, idempotencyKey), not on key alone.
      // This is enforced at the schema level (see 0026 migration).
      // At the store level, the conflict-lookup query must use routeId in the WHERE clause
      // to find the existing event. We verify the query was constructed (it doesn't matter
      // what the where args look like in the mock — we just need to confirm a select was issued).
      const thenable = (val: unknown) => ({ then: (cb: (v: unknown) => void) => cb(val) });
      const insertChain = makeChain();
      insertChain.returning.mockReturnValue(thenable([]));
      const selectChain = makeChain();
      selectChain.all = vi.fn().mockReturnValue([{ eventId: 'existing-event-on-route-A' }]);
      db.insert.mockImplementationOnce(() => insertChain);
      db.select.mockImplementationOnce(() => selectChain);

      const store = createWebhookStore(db as any);
      const result = await store.createEvent({
        routeId: 'route-A', agentId: 'agent-1', payload: {}, headers: {},
        idempotencyKey: 'shared-key',
      });

      // We don't directly assert on the WHERE args (the mock chain is too coarse), but
      // we do assert the dedup lookup happened and returned the route-A event (not
      // some other route's event). This is the observable consequence of AC-2.
      expect(result).toEqual({ kind: 'duplicate', eventId: 'existing-event-on-route-A' });
    });

    it('throws when conflict but no existing event row is found (defense-in-depth)', async () => {
      // Edge case: should not happen in practice (UNIQUE constraint + SELECT both miss),
      // but the contract is to throw rather than fabricate a response.
      const thenable = (val: unknown) => ({ then: (cb: (v: unknown) => void) => cb(val) });
      const insertChain = makeChain();
      insertChain.returning.mockReturnValue(thenable([]));
      // The select().from().where().limit().all() chain needs to resolve to an empty array.
      // We override the chain methods directly to simulate .all() returning the empty array.
      const selectChain = makeChain();
      selectChain.all = vi.fn().mockReturnValue([]);
      db.insert.mockImplementationOnce(() => insertChain);
      db.select.mockImplementationOnce(() => selectChain);

      const store = createWebhookStore(db as any);
      await expect(
        store.createEvent({
          routeId: 'route-1', agentId: 'agent-1', payload: {}, headers: {},
          idempotencyKey: 'phantom-key',
        }),
      ).rejects.toThrow('Idempotency conflict but no existing event found for route=route-1 key=phantom-key');
    });
  });

  describe('listEventsByAgent', () => {
    it('returns events for the agent', async () => {
      const qb = makeChain();
      qb.from.mockReturnValueOnce(qb);
      qb._resolveWhere([{ eventId: 'evt-1' }, { eventId: 'evt-2' }]);
      db.select.mockReturnValueOnce(qb);

      const store = createWebhookStore(db as any);
      const result = await store.listEventsByAgent('agent-1');
      expect(result).toHaveLength(2);
    });

    it('returns empty array when no events exist', async () => {
      const qb = makeChain();
      qb.from.mockReturnValueOnce(qb);
      qb._resolveWhere([]);
      db.select.mockReturnValueOnce(qb);

      const store = createWebhookStore(db as any);
      const result = await store.listEventsByAgent('agent-1');
      expect(result).toHaveLength(0);
    });
  });

  describe('markProcessed', () => {
    it('calls db.update', async () => {
      const store = createWebhookStore(db as any);
      await store.markProcessed('evt-123');
      expect(db.update).toHaveBeenCalled();
    });

    it('throws on DB error', async () => {
      const chain = makeChain();
      chain.set.mockReturnValueOnce(chain);
      chain.where.mockImplementationOnce(() => {
        throw new Error('Mark processed failed');
      });
      db.update.mockReturnValueOnce(chain);

      const store = createWebhookStore(db as any);
      await expect(store.markProcessed('evt-123')).rejects.toThrow('Mark processed failed');
    });
  });

  describe('markFailed', () => {
    it('calls db.update', async () => {
      const store = createWebhookStore(db as any);
      await store.markFailed('evt-456');
      expect(db.update).toHaveBeenCalled();
    });

    it('throws on DB error', async () => {
      const chain = makeChain();
      chain.set.mockReturnValueOnce(chain);
      chain.where.mockImplementationOnce(() => {
        throw new Error('Mark failed DB error');
      });
      db.update.mockReturnValueOnce(chain);

      const store = createWebhookStore(db as any);
      await expect(store.markFailed('evt-456')).rejects.toThrow('Mark failed DB error');
    });
  });
});
