export const forgeCustomToolIds = [
  'get_company_cash_balance',
  'list_company_cash_movements',
  'get_company_cash_summary',
  'list_active_internal_agent_contracts',
  'get_active_internal_agent_contract',
  'list_agent_notifications',
  'get_agent_notification',
  'mark_agent_notification_read',
  'get_github_git_credentials',
  'list_github_repositories',
  'create_github_repository',
  'get_github_repository',
  'list_github_pull_requests',
  'create_github_pull_request',
  'list_github_issues',
  'get_github_issue',
  'create_github_issue',
  'update_github_issue',
  'close_github_issue',
  'reopen_github_issue',
  'list_github_issue_comments',
  'create_github_issue_comment',
  'list_github_labels',
  'add_github_issue_labels',
  'remove_github_issue_labels',
  'list_github_milestones',
  'list_coolify_github_apps',
  'list_coolify_github_app_repositories',
  'list_coolify_github_app_repository_branches',
  'list_coolify_applications',
  'create_coolify_application',
  'get_coolify_application',
  'update_coolify_application',
  'start_coolify_application',
  'stop_coolify_application',
  'restart_coolify_application',
  'delete_coolify_application',
  'list_coolify_application_deployments',
  'get_coolify_deployment_logs',
  'get_coolify_application_logs',
  'list_coolify_application_envs',
  'set_coolify_application_env',
  'delete_coolify_application_env',
  'create_agent_schedule',
  'list_agent_schedules',
  'update_agent_schedule',
  'delete_agent_schedule',
  'list_agent_functions',
  'create_agent_function',
  'update_agent_function',
  'list_agent_roles',
  'create_agent_role',
  'update_agent_role',
  'assign_role_to_function',
  'change_agent_function',
  'change_own_function',
  'list_role_tool_permissions',
  'add_role_tool_permission',
  'remove_role_tool_permission',
  'list_role_workflow_permissions',
  'add_role_workflow_permission',
  'remove_role_workflow_permission',
  'list_available_custom_tools',
  'list_available_workflows',
] as const;

export const forgeWorkflowIds = [
  'hire-internal-agent',
  'terminate-internal-agent',
] as const;

export type ForgeCustomToolId = typeof forgeCustomToolIds[number];
export type ForgeWorkflowId = typeof forgeWorkflowIds[number];
