DROP TABLE `agent_checkpointed_om_states`;--> statement-breakpoint
DROP TABLE `agent_execution_contracts`;--> statement-breakpoint
DROP TABLE `agent_execution_steps`;--> statement-breakpoint
DROP TABLE `agent_home_metric_snapshots`;--> statement-breakpoint
DROP TABLE `agent_long_term_memory_recall_states`;--> statement-breakpoint
DROP TABLE `agent_long_term_memory_states`;--> statement-breakpoint
DROP TABLE `agent_mcp_configs`;--> statement-breakpoint
DROP TABLE `agent_notifications`;--> statement-breakpoint
DROP TABLE `agent_providers`;--> statement-breakpoint
DROP TABLE `agent_roles`;--> statement-breakpoint
DROP TABLE `agent_schedules`;--> statement-breakpoint
DROP TABLE `agents`;--> statement-breakpoint
DROP TABLE `company_cash_ledger`;--> statement-breakpoint
DROP TABLE `company_recurring_payables`;--> statement-breakpoint
DROP TABLE `forge_internal_chat_accounts`;--> statement-breakpoint
DROP TABLE `forge_internal_chat_conversation_members`;--> statement-breakpoint
DROP TABLE `forge_internal_chat_conversations`;--> statement-breakpoint
DROP TABLE `forge_internal_chat_message_attachments`;--> statement-breakpoint
DROP TABLE `forge_internal_chat_message_reads`;--> statement-breakpoint
DROP TABLE `forge_internal_chat_messages`;--> statement-breakpoint
DROP TABLE `llm_model_prices`;--> statement-breakpoint
DROP TABLE `llm_profiles`;--> statement-breakpoint
DROP TABLE `mcp_server_configs`;--> statement-breakpoint
DROP TABLE `role_tool_permissions`;--> statement-breakpoint
DROP TABLE `role_workflow_permissions`;--> statement-breakpoint
DROP TABLE `system_integrations`;--> statement-breakpoint
DROP TABLE `system_llm_defaults`;--> statement-breakpoint
DROP TABLE `system_settings`;